
name: Manual workflow
on:
  workflow_dispatch:
  schedule:
    - cron: '0 21 * * *'
jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@v1
      - name: 'Get weather report'
        run: bash ./weather.shh
          
    

    
