
name: Manual workflow
on:
  workflow_dispatch:
  schedule:
    - cron: '0 21 * * *'
jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@v1
      - name: 'Get weather report'
        run: bash ./weather.sh
      - name: 'Send mail'
        uses: dawidd6/action-send-mail@master
        with:
          server_address: smtp.office365.com
          server_port: 587
          username: ${{ secrets.MAILUSERNAME }}
          password: ${{ secrets.MAILPASSWORD }}
          subject: Shanghai Weather Report
          body: file://result.html
          to: sky2319062020@outlook.com
          from: GitHub Actions
    

    
